services:
  app:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    env_file:
      - .env
    stdin_open: true # Keep STDIN open
    tty: true        # Allocate a pseudo-TTY


volumes:
  node_red_data:
